#### Importer Pandas

In [2]:
import pandas as pd

#### Lire le fichier 'african_econ_crises.csv'
Il se trouve sous le dossier 01-Pandas ou DATA. Faites bien attention à l'endroit où se trouve le fichier .csv ! Si vous n'arrivez pas à le trouver ou à le lire, exécuter le notebook Solutions.

In [5]:
df = pd.read_csv('../DATA/african_econ_crises.csv')

#### Afficher les 5 premières lignes de l'ensemble de données

In [7]:
df.head()

,case,cc3,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
0,1,DZA,Algeria,1870,1,0.052264,0,0,0.0,3.441456,0,0,0,crisis
1,1,DZA,Algeria,1871,0,0.052798,0,0,0.0,14.149140,0,0,0,no_crisis
2,1,DZA,Algeria,1872,0,0.052274,0,0,0.0,-3.718593,0,0,0,no_crisis
3,1,DZA,Algeria,1873,0,0.051680,0,0,0.0,11.203897,0,0,0,no_crisis
4,1,DZA,Algeria,1874,0,0.051308,0,0,0.0,-3.848561,0,0,0,no_crisis

In [ ]:
# Ne rien écrire ici

   case  cc3  country  ...  currency_crises  inflation_crises  banking_crisis
0     1  DZA  Algeria  ...                0                 0          crisis
1     1  DZA  Algeria  ...                0                 0       no_crisis
2     1  DZA  Algeria  ...                0                 0       no_crisis
3     1  DZA  Algeria  ...                0                 0       no_crisis
4     1  DZA  Algeria  ...                0                 0       no_crisis

[5 rows x 14 columns]

#### Combien de pays sont représentés dans cet ensemble de données ?

In [9]:
df['country'].nunique()

13

#### Quels sont les pays représentés dans cet ensemble de données ?

In [10]:
df['country'].unique()

array(['Algeria', 'Angola', 'Central African Republic', 'Ivory Coast',
       'Egypt', 'Kenya', 'Mauritius', 'Morocco', 'Nigeria',
       'South Africa', 'Tunisia', 'Zambia', 'Zimbabwe'], dtype=object)

array(['Algeria', 'Angola', 'Central African Republic', 'Ivory Coast',
       'Egypt', 'Kenya', 'Mauritius', 'Morocco', 'Nigeria',
       'South Africa', 'Tunisia', 'Zambia', 'Zimbabwe'], dtype=object)

#### Quel est le pays dont le taux d'inflation annuel (CPI) est le plus élevé ? Quel était le taux d'inflation ?

In [11]:
df.sort_values('inflation_annual_cpi',ascending=False).head(1)

,case,cc3,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
1053,70,ZWE,Zimbabwe,2008,1,0.002,1,1,0.0,21989695.22,1,1,1,crisis

      case  cc3   country  ...  currency_crises  inflation_crises  banking_crisis
1053    70  ZWE  Zimbabwe  ...                1                 1          crisis

[1 rows x 14 columns]

#### En quelle année le Kenya a-t-il connu sa première crise systémique ?

In [ ]:
df[(df['country']=='Kenya') & (df['systemic_crisis']==1)].sort_values('year')

     case  cc3 country  ...  currency_crises  inflation_crises  banking_crisis
475    35  KEN   Kenya  ...                0                 0          crisis
476    35  KEN   Kenya  ...                0                 0          crisis
477    35  KEN   Kenya  ...                0                 0          crisis
478    35  KEN   Kenya  ...                0                 0          crisis
479    35  KEN   Kenya  ...                1                 0       no_crisis
482    35  KEN   Kenya  ...                1                 1          crisis
483    35  KEN   Kenya  ...                1                 1          crisis
484    35  KEN   Kenya  ...                0                 1          crisis
485    35  KEN   Kenya  ...                0                 0          crisis
486    35  KEN   Kenya  ...                0                 0       no_crisis
487    35  KEN   Kenya  ...                0                 0       no_crisis
488    35  KEN   Kenya  ...                0                 0       no_crisis
489    35  KEN   Kenya  ...                1                 0       no_crisis

[13 rows x 14 columns]

#### Combien de crises systémiques annuelles ont eu lieu dans chaque pays ?

In [12]:
crisis = df[df['systemic_crisis']==1]
crisis.groupby('country').count()['systemic_crisis']

country
Algeria                      4
Central African Republic    19
Egypt                        6
Ivory Coast                  4
Kenya                       13
Morocco                      2
Nigeria                     10
Tunisia                      5
Zambia                       4
Zimbabwe                    15
Name: systemic_crisis, dtype: int64

country
Algeria                      4
Central African Republic    19
Egypt                        6
Ivory Coast                  4
Kenya                       13
Morocco                      2
Nigeria                     10
Tunisia                      5
Zambia                       4
Zimbabwe                    15
Name: systemic_crisis, dtype: int64

#### Pendant combien d'années le Zimbabwe a-t-il connu un défaut de paiement de sa dette extérieure souveraine ?

In [13]:
len(df[(df['country']=='Zimbabwe') & (df['sovereign_external_debt_default']==1)])

30

30

#### En quelle année l'Algérie a-t-elle eu son taux de change le plus élevé ?

In [14]:
df[df['country']=="Algeria"].sort_values('exch_usd',ascending=False).head(1)

,case,cc3,country,year,systemic_crisis,exch_usd,domestic_debt_in_default,sovereign_external_debt_default,gdp_weighted_default,inflation_annual_cpi,independence,currency_crises,inflation_crises,banking_crisis
84,1,DZA,Algeria,2014,0,87.970698,0,0,0.0,2.917,1,0,0,no_crisis

    case  cc3  country  ...  currency_crises  inflation_crises  banking_crisis
84     1  DZA  Algeria  ...                0                 0       no_crisis

[1 rows x 14 columns]